# BuildersPlots Configuration

# Language: ru (Russian) or en (English)
language: "ru"

# Server role: SENDER (test server) or RECEIVER (main server)
server-role: "SENDER"

# Network settings
receiver-host: "localhost"
receiver-port: 5555
sender-port: 5556

# Maximum plot size (in blocks)
max-plot-size:
  width: 256
  height: 256
  length: 256

# Auto-save interval (in minutes)
auto-save-interval: 30

# Directory for storing plots
plots-directory: "plots"

# Debug mode (additional logs)
debug-mode: false