# BuildersPlots Configuration

# Server type (main or test)
server-type: "main"

# Password for inter-server communication (MUST be the same on both servers)
server-password: "change_this_password_to_something_secure"

# Communication settings
communication:
  # Local IP address for server communication
  ip: "localhost"
  port: 25567

# Plot settings
plots:
  # Maximum radius allowed for plots
  max-radius: 100
  # Default world for plots on main server
  main-world: "world"
  # World prefix for plot worlds on test server
  test-world-prefix: "plot_"

world-creation-command: "mv create %world% normal -g flat"