# BuildersPlots Configuration

server:
  # Set to true for the main gameplay server (sender)
  # Set to false for the test server (receiver)
  isMainServer: false
  
  # IP address of the target server
  targetServerIp: "localhost"
  
  # Port for sending data
  sendPort: 25566
  
  # Port for receiving data
  receivePort: 25567

plots:
  # Name of the world where plots will be created (on test server)
  worldName: "plots"
  
  # Maximum plot size (radius)
  maxPlotSize: 200