name: BuildersPlots
version: '${version}'
main: ru.joutak.buildersplots.BuildersPlots
api-version: '1.21'
authors: [joutak]
description: 'Plugin for transferring builds between servers'
folia-supported: true

commands:
  bp:
    description: BuildersPlots main command
    usage: "/<command> [create|list|tp|info|ping|delete]"
    aliases: [buildersplots, plots]