name: BuildersPlots
version: '${version}'
main: com.kostyamops.buildersplots.BuildersPlots
api-version: '1.21'
description: Plot synchronization between main and test servers
folia-supported: true
author: Kostyamops
commands:
  bp:
    description: BuildersPlots main command
    usage: /<command> [create|list|delete] [args...]
    permission: buildersplots.use
    aliases: [buildersplots]