name: ${pluginName}
version: ${version}
main: ru.joutak.buildersplots.BuildersPlots
api-version: '1.21.4'
authors: [Kostyamops]
description: Plot synchronization system for builders
folia-supported: true
commands:
  bp:
    description: BuildersPlots main command
    usage: /bp [create|list|tp|add|remove|delete|sync]
    permission: buildersplots.use
permissions:
  buildersplots.use:
    description: Allows using BuildersPlots commands
    default: true
  buildersplots.admin:
    description: Allows administering BuildersPlots
    default: op
    children:
      buildersplots.use: true