name: BuildersPlots
version: '${version}'
main: com.kostyamops.buildersplots.BuildersPlots
api-version: '1.21'
description: Plot synchronization between main and test servers
folia-supported: true
author: Kostyamops
commands:
  bp:
    description: BuildersPlots main command
    usage: /<command> [create|list|tp|leave|delete|members|help] [args...]
    permission: buildersplots.use
    aliases: [buildersplots]

# Добавьте эти права в секцию permissions
permissions:
  buildersplots.use:
    description: Allows using BuildersPlots commands
    default: true

  buildersplots.command.create:
    description: Allows creating plots
    default: op

  buildersplots.command.delete:
    description: Allows deleting own plots
    default: true

  buildersplots.command.list:
    description: Allows viewing the plot list
    default: true

  buildersplots.command.tp:
    description: Allows teleporting to plots
    default: true

  buildersplots.command.member:
    description: Allows managing plot members
    default: true

  buildersplots.admin.delete.any:
    description: Allows deleting any plot
    default: op

  buildersplots.admin.member.manage:
    description: Allows managing members of any plot
    default: op

  buildersplots.admin.access.all:
    description: Allows access to all plots
    default: op